template:
  name: mlopsimgclass
  use_case: image-classfication
variable_groups:
  - variable_group: devopsforai-aml-vg
    key_values:
      - BASE_NAME: imgj
      - LOCATION: centralus
      - RESOURCE_GROUP: imgjfmlops-RG
      - WORKSPACE_NAME: imgjfmlops-AML-WS
      - AZURE_RM_SVC_CONNECTION: azure-resource-connection
      - WORKSPACE_SVC_CONNECTION: aml-workspace-connection
      - ACI_DEPLOYMENT_NAME: imgjfdmlops-aci
service_connections:
  - service_connection: azure-resource-connection
  - service_connection: aml-workspace-connection
pipelines:
  - pipeline: IAC
    file: environment_setup/iac-create-environment-pipeline-arm.yml
  - pipeline: Model-Train-Register-CI
    file: .pipelines/img_class-ci.yml
  - pipeline: CD
    file: .pipelines/img_class-cd.yml
steps:
  - step: 1_Create_Project
  - step: 2_Import_Repo
  - step: 3_Create_Variable_Groups
  - step: 4_Create_Pipelines
  - Step: 5_Create_Service_Connections
